import "./globals.css";
// import Header from "@/components/header/Header";
import { AuthProvider } from "@/context/AuthContext";
import { MerchantProvider } from "@/context/MerchantContext";
import { CartProvider } from "@/context/CartContext";
import { OrderProvider } from "@/context/OrderContext";
import { ViewProvider } from "@/context/ViewContext";
import { ToastContainer } from "react-toastify";
import Header1 from "@/components/websitecomp/Header1";
import Header from "@/components/header/Header";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir="rtl">
      <body className={` antialiased`}>
        <ToastContainer 
          position="top-right"
          autoClose={3000}
          hideProgressBar={false}
          newestOnTop
          closeOnClick
          rtl={true}
          pauseOnHover
          draggable
          theme="light"
         />

        <MerchantProvider>
          <AuthProvider>
            <CartProvider>
              <OrderProvider>
                <ViewProvider>
                  <div>
                    <Header1 />
                    {/* <Header/> */}
                    {children}
                  </div>
                </ViewProvider>
              </OrderProvider>
            </CartProvider>
          </AuthProvider>
        </MerchantProvider>
      </body>
    </html>
  );
}
